name: Report a bug (English)
description: Don't know Korean? Please use this template to report a bug.
assignees: na1307
labels: bug
body:
  - type: input
    id: version
    attributes:
      label: Package version
      description: Package version causing issue
    validations:
      required: true
  - type: textarea
    id: replicate
    attributes:
      label: Steps to replicate the issue
    validations:
      required: true
  - type: textarea
    id: happens
    attributes:
      label: What happens?
    validations:
      required: true
  - type: textarea
    id: instead
    attributes:
      label: What should have happened instead?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: OS, .NET Runtime version, etc...
    validations:
      required: false
