name: 기능 제안 (한국어)
description: 이런 기능이 있었으면 좋겠다 싶으신가요?
assignees: na1307
labels: enhancement
body:
  - type: input
    id: version
    attributes:
      label: 패키지 버전
      description: 문제가 발생하는 패키지 버전을 알려주세요.
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: 어떤 기능이 있었으면 좋겠나요?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 운영 체제, 닷넷 런타임 버전 등...
    validations:
      required: false
