name: Update lock files for Dependabot .NET SDK PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lockfile:
    name: Update lock files
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && startsWith( github.head_ref, 'dependabot_dotnet_sdk_' )
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACTIONS_PAT }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Restore NuGet packages
        run: dotnet restore --force-evaluate
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          set +e
          git commit -am "Update lock files"
          cmcode=$?
          set -e
          if [ $cmcode -eq 0 ]; then
            git push
          elif [ $cmcode -eq 1 ]; then
            echo "No changes to commit"
            exit 0
          else
            exit $cmcode
          fi;
